### ISSUE TITLE
Low Frame Rate

### ISSUE THREAD

**Issue by kewp** [gheja/untitled13#17]
I'm running this on a Debian VM (can't get it working on windows) but I'm getting about `15 fps` (I'm using MrBoob's **stats.js** to measure). Is this about what you were getting ?

**Comment by kewp** [comment]
I changed the `target_frames_per_second` and `ticks_per_second` to **60** but I'm still only getting around `25 fps`. Also feels a bit janky. Any tips ?

**Comment by gheja** [comment]
Huh, it was quite some time ago but it is mainly due to lack of optimization and size limit.

I believe the game uses very slow methods for drawing/scaling objects, also it is redrawing the whole screen for each frame (maybe the non-visible parts too?), and it is using `window.setInterval()` instead of `window.requestAnimationFrame()` which also degrades the performance. This is why I have limited the frame rate artifically.

**Comment by kewp** [comment]
Hmmm ok, that's interesting. I need to investigate what causes the different frame rates. I like the idea of hexagons, too.

Thanks for the feedback. Will keep at it.
